<?php
require __DIR__ . '/vendor/koraktor/steam-condenser/lib/steam-condenser.php';

$server_status = json_decode(file_get_contents('json/heartlessgaming-serverstatus.json'));
$server_ip = $server_status->gameServerIp;
/*
 * Checking if the server map can be found in the steam api request
 * heartlessgaming-steamapi.json is generated by the server every 10 minutes
 * using this api call url :
 * $steamapi_url = 'http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=' . $server_ip . '&format=json';
 */
$steamapi_file = 'json/heartlessgaming-steamapi.json';

// Getting an array of the online servers from steamapi
$steamapi_json = json_decode(file_get_contents($steamapi_file), true);
$online_servers = $steamapi_json['response']['servers'];
$online_servers_port = [];

// Populating $online_servers_port array to use for server online status detection
foreach ($online_servers as $online_server) {
	array_push($online_servers_port, $online_server['gameport']);
}

// Checking online status against the steamapi result. Also check for type int.
function check_server_status($gameport) {
	global $online_servers_port;

	if (in_array($gameport, $online_servers_port, TRUE)) {
		return true;
	}
}

/*
 * Get all the information of a source engine game.
 * Return : array with all the server info
 */
function get_source_server_info($port) {
	global $server_ip;

	$server = new SourceServer( $server_ip, $port );
	$server->initialize();
	return $server->getServerInfo();
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Game server status of the Heartless Gaming pc gaming community.">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<title>Game Server Status | Heartless Gaming</title>
</head>
<body>
	<header class="page-header flex-container box">
			<h1 class="page-header__title">Game Server Status</h1>
			<a href="https://www.heartlessgaming.com" class="page-header__link">
				<img src="img/hearltess-gaming-logo.svg" alt="Logo Heartless Gaming" class="page-header__logo">
			</a>
	</header>
	<main class="page-content">
	<?php foreach ($server_status as $gamename => $gameservers_info) : ?>
		<section class="game-server box">
			<header class="game-server__header">
				<h2 class="game-server__title h3-like"><?php echo $gamename ?><img src="img/arrow.svg" class="game-server__hide is-hidden js-gameserver"></h2>
			</header>
			<div class="js-gameserver-list">
			<?php foreach ($gameservers_info as $game_info) : ?>
				<div class="game-server__info flex-container">
					<p class="game-server__name"><?php echo $game_info->servername ?></p>
					<p class="game-server__players">
						<?php if (check_server_status($game_info->port) && $game_info->isSourceGame) {
								echo get_source_server_info($game_info->port)['numberOfPlayers'] . ' / ' . get_source_server_info($game_info->port)['maxPlayers'];
						} ?>
					</p>
					<p class="game-server__ip"><?php echo $server_ip . ':' . $game_info->port ?></p>
				<?php if (check_server_status($game_info->port)) : ?>
					<?php if (true === true) : ?>
						<p class="game-server__status game-server__updating">Updating</p>
					<?php else: ?>
						<a href="steam://connect/<?php echo $server_ip . ':' . $game_info->port ?>" class="game-server__status game-server__join btn">Join</a>
					<?php endif; ?>
				<?php else : ?>
					<p class="game-server__status game-server__offline">Offline</p>
				<?php endif; ?>
				</div>
			<?php endforeach; ?>
			</div>

		</section>
	<?php endforeach; ?>
	</main>
	<footer class="page-footer box">
		<p>Game servers online status are checked every 10 minutes.</p>
		<p>Feel free to contact us by email <span class="page-footer__mail">contact [at] heartlessgaming.com</span> if you have a problem or a sugestion to make the game servers better.</p>
		<p>The source code of this website is available on <a href="https://github.com/heartless-gaming/server-status">github</a></p>
		<p>Play more, Care less, Be an Heartless.</p>
	</footer>
	<script src="../node_modules/jquery/dist/jquery.min.js"></script>
	<script src="js/script.js"></script>
</body>
</html>
